slaves:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: 10.0.0.5:5002/sparkimage
  privileged: true
  stdin_open: true
master:
  ports:
  - ${ui_port}:8080/tcp
  - ${spark_port}:7077/tcp
  - ${sshd_port}:22/tcp
  - ${restful_port}:6066/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: ${host_label}
  tty: true
  log_opt: {}
  image: 10.0.0.5:5002/sparkimage
  links:
  - 'slaves:'
  privileged: true
  stdin_open: true
