zabbix-server:
  image: index.youruncloud.com/catalog/zabbix-server:v1.0.0
  restart: always
  ports:
   - 10051:10051
   - 10052:10052
   - 2812:2812
   - 8082:80
  volumes:
   - /etc/localtime:/etc/localtime:ro
  labels:
    appsoar.dashboard.entrypoint.name1: http://{ip}:8082/zabbix