.catalog:
  name: "Kibana"
  version: "4.4.2-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"
    - variable: "webport"
      description: "Web Access Port"
      label: "Web Access Port:"
      type: "int"
      required: true
      default: 80
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601
