zabbix-agent:
  image: index.youruncloud.com/catalog/zabbix-agent-xxl-limited:v1.0.0
  restart: always
  hostname: ${agent_hostname}
  labels:
      io.rancher.scheduler.global: 'true'
  ports:
   - 10050:10050
  environment:
   - ZA_Server=${zabbix_serverip}
   - ZA_ServerActive=${zabbix_serverip_active}
  volumes:
   - /:/rootfs
   - /etc/localtime:/etc/localtime:ro
